# Generated by Django 4.1 on 2022-11-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'AlertEmails',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('interval', models.IntegerField(default=30)),
                ('running', models.BooleanField(default=False)),
                ('success_status', models.IntegerField(blank=True, null=True)),
                ('timeout', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'Monitors',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='MonitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(max_length=300)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monitor')),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='MonitorAlertEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alertemail')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monitor')),
            ],
            options={
                'db_table': 'MTM_MonitorsAlertEmails',
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='alert_emails',
            field=models.ManyToManyField(through='api.MonitorAlertEmail', to='api.alertemail'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.page'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
