# Generated by Django 4.1 on 2022-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='interval',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='success_status',
            field=models.IntegerField(default=200),
        ),
    ]
