# Generated by Django 4.1 on 2022-12-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_monitor_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorevent',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorevent',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
