# Generated by Django 4.1 on 2023-01-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_monitorevent_created_time_monitorevent_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorevent',
            name='failure_start',
            field=models.BooleanField(default=False),
        ),
    ]
