# Generated by Django 4.1 on 2023-02-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_monitorevent_failure_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMonitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monitor')),
            ],
            options={
                'db_table': 'MTM_UserPageMonitors',
            },
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('href_link', models.CharField(blank=True, max_length=300, null=True)),
                ('icon_link', models.CharField(blank=True, max_length=500, null=True)),
                ('monitors', models.ManyToManyField(through='api.PageMonitors', to='api.monitor')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.page')),
            ],
            options={
                'db_table': 'UserPage',
            },
        ),
        migrations.AddField(
            model_name='pagemonitors',
            name='user_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userpage'),
        ),
    ]
