# Generated by Django 4.1 on 2023-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pagemonitors_userpage_pagemonitors_user_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='icon_link',
            field=models.ImageField(blank=True, null=True, upload_to='userpages/'),
        ),
    ]
