# Generated by Django 4.1 on 2023-02-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userpage_user_alter_userpage_icon_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pages_marketplace/'),
        ),
        migrations.AddField(
            model_name='page',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
