# Generated by Django 4.1 on 2023-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_page_link_page_picture_page_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
