# Generated by Django 4.1 on 2023-03-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userpage_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='html_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
