# Generated by Django 4.1 on 2023-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userpage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorevent',
            name='failure_end',
            field=models.BooleanField(default=False),
        ),
    ]
