# Generated by Django 4.1 on 2023-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_monitorevent_failure_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='down',
            field=models.BooleanField(default=False),
        ),
    ]
