# Generated by Django 4.1 on 2023-03-29 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_monitor_down'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('uptime', models.FloatField(default=0)),
                ('response', models.FloatField(default=0)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monitor')),
            ],
            options={
                'db_table': 'EventStats',
            },
        ),
    ]
