# Generated by Django 4.1 on 2023-02-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_notification_notificationuser_notification_seen_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
