# Generated by Django 4.1 on 2023-02-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_notification_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUserDeleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Notification_Deleted',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_by',
            field=models.ManyToManyField(related_name='notification_deleted_by', through='website.NotificationUserDeleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationuserdeleted',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.notification'),
        ),
        migrations.AddField(
            model_name='notificationuserdeleted',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
