# Generated by Django 4.1 on 2023-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_notificationuserdeleted_notification_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
