# Generated by Django 4.1 on 2023-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, default='Free', max_length=50, null=True),
        ),
    ]
