# Generated by Django 4.1 on 2023-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_user_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Pro', 'Pro')], default='Free', max_length=50, null=True),
        ),
    ]
