# Generated by Django 4.1 on 2023-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_last_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
