# Generated by Django 4.1 on 2023-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_user_card_last_digit_user_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_sub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
