# Generated by Django 4.1 on 2023-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_user_stripe_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Business', 'Business')], default='Free', max_length=50, null=True),
        ),
    ]
