# Generated by Django 4.1 on 2023-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_user_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
