version: "3"
services:
  web:
    container_name: main
    build: ./backend/
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/code/
      - ./creds.json:/code/creds.json
  jobs:
    container_name: jobs
    build: ./jobs/
    restart: always
    volumes:
      - ./jobs/:/code/
  db:
    container_name: database
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: monitoring
      MYSQL_USER: musk
      MYSQL_PASSWORD: musk
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./monitordb:/var/lib/mysql
    ports:
      - 20000:3306
  server:
    image: nginx:1.20-alpine
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./backend/static/:/static/"
      - "./backend/media/:/media/"
      - "/etc/letsencrypt/live/www.statuschecks.net/fullchain.pem:/letsencrypt/fullchain.pem"
      - "/etc/letsencrypt/live/www.statuschecks.net/privkey.pem:/letsencrypt/privkey.pem"
    ports:
      - 80:80
      - 443:443
