# Generated by Django 4.1 on 2022-10-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('interval', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorAlertEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alertemail')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.monitor')),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='alert_emails',
            field=models.ManyToManyField(through='api.MonitorAlertEmail', to='api.alertemail'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.page'),
        ),
    ]
