# Generated by Django 4.1 on 2023-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], max_length=20)),
                ('price', models.FloatField(default=0)),
                ('monitors', models.IntegerField(default=5)),
            ],
        ),
    ]
