# Generated by Django 4.1 on 2023-03-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro')], max_length=20),
        ),
    ]
