# Generated by Django 4.1 on 2023-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='alert_emails',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='plan',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Business', 'Business')], max_length=20),
        ),
    ]
