# Generated by Django 4.1 on 2023-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_plan_alert_emails_plan_interval_plan_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.CharField(max_length=300)),
                ('public', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
