# Generated by Django 4.1 on 2023-02-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'background_task',
                'managed': False,
            },
        ),
    ]
